const Router = require('express')
const router = new Router()
const userController = require('../controllers/userController') 
const authMiddleware = require('../middleware/authMiddleware')

router.post('/registration', userController.registration)
router.post('/login', userController.login)
router.get('/auth', authMiddleware,userController.check)
router.post('/checkPassword', authMiddleware, userController.CheckPassword)
router.get('/profile', authMiddleware,userController.getUserInfo )
router.delete('/delete:id',userController.delete )
router.patch('/update', userController.UpdateUser)
router.post('/review', authMiddleware,userController.createReview)
router.get('/userReviews',authMiddleware,userController.getUserReviews)
router.get('/tourReviews/:tourId',userController.getTourReviews)
router.patch('/reviewUpdate',userController.updateReview)
router.delete('/deleteReview/:formReviews', userController.delUserReview)
module.exports = router